encoding: utf-8
safe:        false
base-url:    http://vim-jp.org

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   date

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "superscript"]
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

exclude:
  - 'scripts'
  - 'Gemfile'
  - 'README.md'
  - 'vendor'

gems:
  - jemoji
  - jekyll-sitemap

hotkeys: true

comment: true
permalink: /:categories/:year/:month/:day/:title

disqus: true

