encoding: utf-8
safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    http://vim-jp.org

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   date

redcarpet:
  extensions: ["tables", "autolink"]  

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

exclude: scripts

downloads:
  vim73w32:
    title: Windows 32ビット
    version: 7.3.865
    info: +kaoriya, 14MB ZIP
  vim73w64:
    title: Windows 64ビット
    version: 7.3.865
    info: +kaoriya, 14MB ZIP
  vim73win:
    title: Windows 32ビット/64ビット
    version: 7.3.865
    info: +kaoriya, 14MB ZIP
  vim73mac:
    title: MacOSX 10.7/10.8
    version: 7.3.754
    info: +macvim-kaoriya, 11MB
