encoding: utf-8
safe:        false
base-url:    http://vim-jp.org

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   date

redcarpet:
  extensions: ["tables",  "autolink",  "strikethrough",  "superscript"]
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

exclude:
  - 'scripts'
  - 'Gemfile'

downloads:
  vim74w32:
    title: Windows 32ビット
    version: '7.4'
    info: +kaoriya, 14MB ZIP
  vim74w64:
    title: Windows 64ビット
    version: '7.4'
    info: +kaoriya, 15MB ZIP
  vim74win:
    title: Windows 32ビット/64ビット
    version: '7.4'
    info: +kaoriya, 14/15MB ZIP
  vim74mac:
    title: MacOSX 10.7/10.8
    version: 7.4a.009
    info: +macvim-kaoriya, 11MB
